name: End-to-end tests
on: [push]
jobs:
 cypress-run:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v1

     - name: Run backend
       uses: actions/setup-node@v1
       
       with:
         cache-dependency-path: backend/package-lock.json
         node-version: ${{ matrix.node-version }}
     - name: Start Server
       working-directory: ./backend
       run: |
        npm install
        npm run start &

     - name: Cypress run
       uses: cypress-io/github-action@v4.1.0
       with:
         config-file: cypress.config.ts
         record: true
         start: yarn --cwd ./nuntius-pro-app run start
         build: yarn --cwd ./nuntius-pro-app run build
         wait-on: http://localhost:3000
         working-directory: ./nuntius-pro-app
